import { type CAC, type Command } from 'cac';
import { executeFastlane } from './executor.js';
import { withIpcServer } from './ipc_server.js';
import { withEnv } from './env_resolutions/index.js';
import { descriptionLog, exampleLog } from './logger.js';

/**
 * Option definition for a Fastlane action CLI command.
 */
export interface FastlaneActionOption {
  /**
   * Option flag name(s), e.g. '-t, --track <track>' or '--package_name <package_name>'
   */
  option?: string;
  name?: string;
  /**
   * Description of the option shown in CLI help
   */
  description: string;
}

/**
 * Parameters for registering a Fastlane action as a CAC command.
 */
export interface RegisterFastlaneActionOptions {
  /**
   * The name of the Fastlane action to execute (e.g. 'check_google_play_console')
   */
  actionName: string;
  /**
   * Optional custom command name on the CLI (defaults to actionName)
   */
  commandName?: string;
  /**
   * Description of the command shown in CLI help
   */
  description: string;
  /**
   * List of CLI options with their flags and descriptions
   */
  options?: FastlaneActionOption[];
  /**
   * List of example command invocations shown in CLI help
   */
  examples?: string[];
}

/**
 * Converts parsed CLI options and positional args into Fastlane key:value arguments.
 */
function formatFastlaneArgs(
  args: string[] = [],
  parsedOptions: Record<string, any> = {},
): string[] {
  const actionArgs: string[] = [...args];
  const passedKeys = new Set(
    args
      .filter((a) => typeof a === 'string' && a.includes(':'))
      .map((a) => a.split(':')[0]),
  );

  for (const [rawKey, value] of Object.entries(parsedOptions)) {
    // Ignore short flags (single letter aliases generated by CAC), internal CAC properties, and global flags
    if (
      rawKey.length <= 1 ||
      ['--', 'help', 'version', 'production'].includes(rawKey)
    ) {
      continue;
    }

    // Convert camelCase and kebab-case to snake_case for Fastlane
    const snakeKey = rawKey
      .replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
      .replace(/-/g, '_');

    if (passedKeys.has(snakeKey)) {
      continue;
    }

    if (value !== undefined && value !== null) {
      actionArgs.push(`${snakeKey}:${value}`);
      passedKeys.add(snakeKey);
    }
  }

  return actionArgs;
}

/**
 * Registers a Fastlane action as a standalone CAC command with options and examples.
 *
 * @example Object style
 * ```ts
 * registerFastlaneAction(cli, {
 *   actionName: 'check_google_play_console',
 *   description: 'Check app status on Google Play Console',
 *   options: [
 *     { option: '-t, --track <track>', description: 'Play Store track name' },
 *     { option: '-p, --package_name <package_name>', description: 'Application ID / package name' },
 *   ],
 *   examples: [
 *     'cmd-bin check_google_play_console --track internal',
 *   ],
 * });
 * ```
 *
 * @example Positional style
 * ```ts
 * registerFastlaneAction(
 *   cli,
 *   'check_google_play_console',
 *   'Check app status on Google Play Console',
 *   [{ option: '--track <track>', description: 'Track name' }],
 *   ['cmd-bin check_google_play_console --track internal']
 * );
 * ```
 */
export function registerFastlaneAction(
  cli: CAC,
  actionNameOrConfig: string | RegisterFastlaneActionOptions,
  description?: string,
  options: FastlaneActionOption[] = [],
  examples: string[] = [],
): Command {
  let actionName: string;
  let commandName: string;
  let commandDesc: string;
  let commandOptions: FastlaneActionOption[];
  let commandExamples: string[];

  if (typeof actionNameOrConfig === 'object') {
    actionName = actionNameOrConfig.actionName;
    commandName = actionNameOrConfig.commandName || actionName;
    commandDesc = actionNameOrConfig.description;
    commandOptions = actionNameOrConfig.options || [];
    commandExamples = actionNameOrConfig.examples || [];
  } else {
    actionName = actionNameOrConfig;
    commandName = actionName;
    commandDesc = description || '';
    commandOptions = options;
    commandExamples = examples;
  }

  const command = cli
    .command(`${commandName} [...args]`, descriptionLog(commandDesc))
    .option(
      '-p, --production',
      descriptionLog('Use production environment variables (_PROD suffix)'),
    )

  for (const opt of commandOptions) {
    const flag = opt.option || opt.name;
    if (flag) {
      command.option(flag, descriptionLog(opt.description));
    }
  }

  for (const ex of commandExamples) {
    command.example(exampleLog(ex));
  }

  const commandHandler = withEnv(
    withIpcServer(
      async (args: string[] = [], parsedOptions: Record<string, any> = {}) => {
        const actionArgs = formatFastlaneArgs(args, parsedOptions);

        try {
          await executeFastlane(['run', actionName, ...actionArgs], parsedOptions);
        } catch (e: unknown) {
          if (e instanceof Error) console.error(e.message);
          else console.error(e);
        }
      },
    ),
  );

  command.action(commandHandler);

  return command;
}

/**
 * Creates a helper bound to a specific CAC instance for registering Fastlane actions.
 */
export const createFastlaneActionRegistrar = (cli: CAC) => {
  return (
    actionNameOrConfig: string | RegisterFastlaneActionOptions,
    description?: string,
    options?: FastlaneActionOption[],
    examples?: string[],
  ) =>
    registerFastlaneAction(
      cli,
      actionNameOrConfig as any,
      description,
      options,
      examples,
    );
};
